# Dev
alias c='cursor'

# Java
alias j11='export JAVA_HOME=$JAVA_11_HOME && java -version'
alias j17='export JAVA_HOME=$JAVA_17_HOME && java -version'

# Android
alias mas='mirror_android_screen'
alias ras='record_android_screen'
alias ads='android_device_serial'
alias logcat='logcat-color'

# Npm
alias ni='npm i'
alias nid='npm i -D'
alias ns='npm start'
alias nt='npm test'
alias nr='npm run'
alias nra='npm run android'
alias nrb='npm run build'
alias nrc='npm run clean'
alias nrd='npm run dev'
alias nrdp='npm run deploy'
alias nri='npm run ios'
alias nrl='npm run lint'
alias nrs='npm run serve'
alias nd='npm run dev'
alias nx='npx'
alias nu='npm uninstall'

# Pnpm
alias pi='pnpm i'
alias pid='pnpm i -D'
alias ps='pnpm start'
alias pt='pnpm test'
alias pr='pnpm run'
alias pra='pnpm run android'
alias prb='pnpm run build'
alias prc='pnpm run clean'
alias prd='pnpm run dev'
alias prdp='pnpm run deploy'
alias pri='pnpm run ios'
alias prl='pnpm run lint'
alias prs='pnpm run serve'
alias pd='pnpm run dev'
alias px='pnpm dlx'
alias pu='pnpm remove'

# yarn
alias yi='yarn i'
alias yid='yarn i -D'
alias ys='yarn start'
alias yt='yarn test'
alias yr='yarn run'
alias yra='yarn run android'
alias yrb='yarn run build'
alias yrc='yarn run clean'
alias yrd='yarn run dev'
alias yrdp='yarn run deploy'
alias yri='yarn run ios'
alias yrl='yarn run lint'
alias yrs='yarn run serve'
alias yd='yarn run dev'
alias yx='yarn dlx'
alias yu='yarn remove'

# Bun
alias bi='bun i'
alias bid='bun i -D'
alias bs='bun start'
alias bt='bun test'
alias br='bun run'
alias bx='bun dlx'
alias bu='bun remove'
alias bl='bun lint'
alias bra='bun run android'
alias brb='bun run build'
alias brc='bun run clean'
alias brd='bun run dev'
alias brdp='bun run deploy'
alias bri='bun run ios'
alias brs='bun run serve'

# Python
alias p3='python3'
alias pip='pip3'

# Shell
alias oz='c $ZSH_CONFIG'
alias ez='c $ZDOTDIR/.zshrc'
alias exz='exec zsh'
alias sz='source $ZDOTDIR/.zshrc'

# Git
alias ga='git add'
alias gcm='git commit -m'
alias gz='git cz'
alias gpl='git pull'
alias gpsu='git push -u origin $(gccb | pbpaste)'
alias gps='git push'
alias gst='git status'
alias gf='git fetch'
alias gd='git diff'
alias gl='git lg'
alias glo='git log --oneline'
alias gsw='git switch'
alias gco='git checkout'
alias gbr='git br'
alias gcp='git cherry-pick'
alias gccb='git rev-parse --abbrev-ref HEAD | pbcopy'
alias eg='c ~/.gitconfig'
alias lg='lazygit'
alias gcz='git cz'
alias gra='git_remove_all_changes'
alias gr='git reset'

# System
alias cls='clear'
alias ip='ifconfig | grep "inet 1"'
alias fo='force_open'
alias fc='force_close'
alias ls="lsd"
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias lp='print -l $path'
alias uz='unzip_file'
alias ssha='ssh_add'
alias brewl='brew_log'

# Opening Folders
alias o='open .'
alias odwn='open $HOME/Downloads'
alias odt='open $HOME/Desktop'
alias odc='open $HOME/Documents'
alias oss='open $HOME/Desktop/All\ Items/Screenshots'
alias rn='rename'

# Zip Project
alias zp='zipproject'

# React Native
alias rdo='adb shell input keyevent 82'

# Commented
# alias cin='code-insiders'
# alias mage='php bin/magento'
# alias sf='spotify'
# alias sfp='spotify play'
# alias sfps='spotify pause'
# alias sfpr='spotify prev'
# alias sfn='spotify next'
# alias sft='spotify toggle'
